"""BUNDLED PINNED COPY. Canonical source: default-settlement-verifier/portable/portable_sar_verify.py, pinned at commit d77af99c341f1dca85258f194ee7fc12f7aa6af0 (2026-07-23).
Do not edit this file directly -- edit the canonical source and re-pin.
See reports/strategy/sar-portable-verification-remediation-20260723.md
in the morpheus repository for the drift-check process.

Canonical Portable SAR (six-field) inbound verifier.

Source of truth: default-settlement-verifier/portable/portable_sar_verify.py
Consumers (settlement-witness, defaultsettle-cli, the SettlementWitness
skill) bundle a pinned copy of this exact file and record the source
commit hash they were pinned from. Do not fork the logic independently.

Scope and invariants (see reports/strategy/sar-portable-verification-
remediation-20260723.md for the full design and evidence):

- Verifies ONLY the original/portable six-field SAR v0.1 profile:
  task_id_hash, verdict, confidence, reason_code, ts, verifier_kid.
- `counterparty` and `_ext`, if present, are NEVER included in the signed
  core and are ALWAYS reported back as unsigned metadata. This module
  never reports a wallet/counterparty binding.
- Does not touch, import, or depend on Default Settlement's wallet-bound
  verification logic (`_sar_core_without_sig` / `_sar_verify_receipt_v0_1`
  and its skill/MCP/CLI mirrors). The two are separate code paths by
  design; this module must never be merged with or substituted for them.
- Profile *candidacy* (declared via `receipt_version` + `sig_alg`) is
  necessary but not sufficient. A `key_policy(kid)` callable must resolve
  `{"pubkey": bytes, "profiles": set[str], "source": str}` or `None`, and
  the receipt's declared candidate profile must be in that key's
  authorized `profiles` set before any digest/signature check runs. An
  explicit caller-requested profile can only narrow this check (must
  agree with the envelope-declared candidate); it can never override a
  key/profile authorization mismatch.
- No trial-and-error canonicalization: the six-field core is
  reconstructed exactly once per verification call. There is no fallback
  to a different field set if the first reconstruction fails to match.
- Rejection outcomes are distinct and ordered: malformed envelope ->
  unrecognized version/alg -> unknown key -> profile not authorized ->
  receipt_id mismatch -> invalid signature. Unknown-key and
  profile-authorization failures are always reported before any
  cryptographic (digest/signature) failure, and are never conflated with
  one another.
"""
from __future__ import annotations

import base64
import hashlib
from dataclasses import dataclass, field
from typing import Any, Callable, Optional

try:
    import jcs
except ImportError as exc:  # pragma: no cover - environment guard
    raise ImportError(
        "portable_sar_verify requires the 'jcs' package (RFC 8785 JCS)"
    ) from exc

from cryptography.exceptions import InvalidSignature as _CryptoInvalidSignature
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey

PORTABLE_PROFILE_ID = "portable-sar-v0.1"

PORTABLE_CORE_FIELDS = (
    "task_id_hash",
    "verdict",
    "confidence",
    "reason_code",
    "ts",
    "verifier_kid",
)

PORTABLE_ENVELOPE_REQUIRED = (
    "receipt_version",
    "receipt_id",
    "sig_alg",
    "sig",
) + PORTABLE_CORE_FIELDS

SUPPORTED_RECEIPT_VERSIONS = ("0.1",)
SUPPORTED_SIG_ALG = "Ed25519"


@dataclass
class KeyPolicyEntry:
    pubkey: bytes
    profiles: frozenset
    source: str


KeyPolicy = Callable[[str], Optional[KeyPolicyEntry]]


@dataclass
class VerificationResult:
    status: str  # see STATUS_* constants below
    reason: str = ""
    profile: Optional[str] = None
    signed_fields: tuple = ()
    key_kid: Optional[str] = None
    trust_source: Optional[str] = None
    unsigned_claims: dict = field(default_factory=dict)
    wallet_binding_attested: bool = False
    computed_receipt_id: Optional[str] = None

    def is_verified(self) -> bool:
        return self.status == STATUS_VERIFIED

    def to_dict(self) -> dict:
        return {
            "status": self.status,
            "reason": self.reason,
            "profile": self.profile,
            "signed_fields": list(self.signed_fields),
            "key_kid": self.key_kid,
            "trust_source": self.trust_source,
            "unsigned_claims": self.unsigned_claims,
            "wallet_binding_attested": self.wallet_binding_attested,
            "computed_receipt_id": self.computed_receipt_id,
        }


STATUS_VERIFIED = "VERIFIED"
STATUS_MALFORMED = "REJECTED_MALFORMED"
STATUS_UNSUPPORTED_PROFILE = "UNSUPPORTED_PROFILE"
STATUS_UNKNOWN_KEY = "REJECTED_UNKNOWN_KEY"
STATUS_PROFILE_NOT_AUTHORIZED = "REJECTED_PROFILE_NOT_AUTHORIZED"
STATUS_RECEIPT_ID_MISMATCH = "REJECTED_RECEIPT_ID_MISMATCH"
STATUS_INVALID_SIGNATURE = "REJECTED_INVALID_SIGNATURE"
STATUS_NOT_CANDIDATE = "REJECTED_NOT_PORTABLE_CANDIDATE"


def _detect_candidate_profile(receipt: Any) -> tuple[Optional[str], Optional[str]]:
    """Declared-metadata-only classification. Never itself an authorization."""
    if not isinstance(receipt, dict):
        return None, "receipt is not a JSON object"
    has_version = "receipt_version" in receipt
    has_alg = "sig_alg" in receipt
    if not (has_version and has_alg):
        return None, (
            "receipt does not declare portable-sar-v0.1 envelope metadata "
            "(receipt_version + sig_alg); this verifier supports no other "
            "inbound profile"
        )
    if receipt.get("receipt_version") not in SUPPORTED_RECEIPT_VERSIONS:
        return None, f"unrecognized receipt_version: {receipt.get('receipt_version')!r}"
    if receipt.get("sig_alg") != SUPPORTED_SIG_ALG:
        return None, f"unrecognized sig_alg: {receipt.get('sig_alg')!r}"
    return PORTABLE_PROFILE_ID, None


def _build_core(receipt: dict) -> dict:
    return {k: receipt[k] for k in PORTABLE_CORE_FIELDS}


def verify_portable_sar_receipt(
    receipt: Any,
    key_policy: KeyPolicy,
    requested_profile: Optional[str] = None,
) -> VerificationResult:
    """Deterministically verify a single inbound Portable SAR receipt.

    `key_policy(kid)` must return a `KeyPolicyEntry` (or a plain object
    with `.pubkey` bytes, `.profiles` a set/frozenset of profile id
    strings, and `.source` a human-readable string) or `None` if the kid
    is unknown/untrusted. No default trust store is baked into this
    module; callers must supply their own explicit policy.
    """
    candidate, candidate_err = _detect_candidate_profile(receipt)

    if requested_profile is not None:
        if candidate != requested_profile:
            return VerificationResult(
                status=STATUS_NOT_CANDIDATE,
                reason=(
                    f"requested profile {requested_profile!r} disagrees with "
                    f"envelope-declared candidate {candidate!r}"
                    + (f" ({candidate_err})" if candidate_err else "")
                ),
            )

    if candidate is None:
        return VerificationResult(status=STATUS_NOT_CANDIDATE, reason=candidate_err or "not a candidate")

    if candidate != PORTABLE_PROFILE_ID:
        return VerificationResult(status=STATUS_UNSUPPORTED_PROFILE, reason=f"profile {candidate!r} not implemented")

    missing = [f for f in PORTABLE_ENVELOPE_REQUIRED if f not in receipt]
    if missing:
        return VerificationResult(status=STATUS_MALFORMED, reason=f"missing required envelope fields: {missing}")

    core = _build_core(receipt)
    try:
        canonical = jcs.canonicalize(core)
    except Exception as exc:  # noqa: BLE001 - surfaced as a malformed result, not raised
        return VerificationResult(status=STATUS_MALFORMED, reason=f"canonicalization failed: {exc}")

    digest = hashlib.sha256(canonical).digest()
    expected_receipt_id = "sha256:" + digest.hex()

    kid = receipt.get("verifier_kid")
    entry = key_policy(kid)
    if entry is None:
        return VerificationResult(
            status=STATUS_UNKNOWN_KEY,
            reason=f"unknown or untrusted key: {kid!r}",
            computed_receipt_id=expected_receipt_id,
        )

    entry_profiles = getattr(entry, "profiles", None)
    if entry_profiles is None and isinstance(entry, dict):
        entry_profiles = entry.get("profiles")
    entry_source = getattr(entry, "source", None)
    if entry_source is None and isinstance(entry, dict):
        entry_source = entry.get("source")
    entry_pubkey = getattr(entry, "pubkey", None)
    if entry_pubkey is None and isinstance(entry, dict):
        entry_pubkey = entry.get("pubkey")

    if PORTABLE_PROFILE_ID not in (entry_profiles or ()):
        return VerificationResult(
            status=STATUS_PROFILE_NOT_AUTHORIZED,
            reason=(
                f"key {kid!r} is known (source={entry_source}) but not authorized "
                f"for profile {PORTABLE_PROFILE_ID!r} "
                f"(authorized for: {sorted(entry_profiles or ())})"
            ),
            computed_receipt_id=expected_receipt_id,
        )

    receipt_id = receipt.get("receipt_id")
    if not isinstance(receipt_id, str) or not receipt_id.startswith("sha256:"):
        return VerificationResult(status=STATUS_MALFORMED, reason="receipt_id missing 'sha256:' prefix")
    if receipt_id != expected_receipt_id:
        return VerificationResult(
            status=STATUS_RECEIPT_ID_MISMATCH,
            reason=f"expected {expected_receipt_id}, got {receipt_id}",
            computed_receipt_id=expected_receipt_id,
        )

    sig_field = receipt.get("sig", "")
    if not isinstance(sig_field, str) or not sig_field.startswith("base64url:"):
        return VerificationResult(status=STATUS_MALFORMED, reason="sig missing 'base64url:' prefix")

    try:
        sig_bytes = base64.urlsafe_b64decode(sig_field.split("base64url:", 1)[1] + "==")
        pub = Ed25519PublicKey.from_public_bytes(entry_pubkey)
        pub.verify(sig_bytes, digest)
    except (_CryptoInvalidSignature, Exception) as exc:  # noqa: BLE001
        return VerificationResult(
            status=STATUS_INVALID_SIGNATURE,
            reason=f"cryptographically invalid signature: {exc}",
            computed_receipt_id=expected_receipt_id,
        )

    unsigned_claims: dict = {}
    counterparty = receipt.get("counterparty")
    if isinstance(counterparty, str) and counterparty.strip():
        unsigned_claims["counterparty"] = counterparty.strip()
    if "_ext" in receipt:
        unsigned_claims["_ext"] = receipt["_ext"]

    return VerificationResult(
        status=STATUS_VERIFIED,
        profile=PORTABLE_PROFILE_ID,
        signed_fields=PORTABLE_CORE_FIELDS,
        key_kid=kid,
        trust_source=entry_source,
        unsigned_claims=unsigned_claims,
        wallet_binding_attested=False,
        computed_receipt_id=expected_receipt_id,
        reason="counterparty, if present, is unsigned metadata and is not an attested wallet binding under this profile",
    )
